### ISSUE TITLE
display of dates

### ISSUE THREAD

**Issue by prabuvenkat** [Lighthouse-io/react-visjs-timeline#18] opened 2017-05-31 10:34 UTC
**Everything is 1 month early !!**

I am encountering a weird problem that my items always get pulled by one month! for eg. if i specify <code>'2017/02/01'</code> the item appears in the month of Jan !
![visjs-tmline-wo-minmax](https://cloud.githubusercontent.com/assets/2300563/26628055/e041a01c-45fc-11e7-9c35-4b793177a0a1.png)

I am initialising the start/end dates for each event in this format:
<code>
{
  start: new Date('2018/01/01'),
  end: new Date('2018/10/01'),
}
</code>

**Year in time axis**
Whenever I specify min/max or start/stop in my options, the year displayed at the start is displayed incorrectly. 
![visjs-tmline-w-minmax](https://cloud.githubusercontent.com/assets/2300563/26628063/e6925632-45fc-11e7-8e9a-ce0cee66857c.png)

**Comment by jonathanchrisp** [comment] 2017-05-31 10:48
Hey @prabuvenkat, thanks for raising the issue. If possible can you get back to me with the following information:

* Code snippet highlighting how you are initializing the timeline
* Let us know which version of the library you are using
* Let us know which version of vis.js you are using as a peer dependency

**Comment by prabuvenkat** [comment] 2017-05-31 11:11
package.json:

> "vis": "4.20.0",
> "react-visjs-timeline": "1.3.3",

Initialization:
> const dpStart = new Date('2018/01/01');
> const dpEnd = new Date('2019/12/30');
>
> const options = {
>  width: '100%',
>  selectable: true,
>  editable: true,
>  /* uncomment this or the min/max lines for the 2nd part of the issue 
>  start: dpStart,
>  end: dpEnd,
>  min: dpStart,
>  max: dpEnd,
>  \*/
>  moveable: false,
>  stack: true,
> groupOrder: 'content',
> format: {
>    minorLables: {
>      month: 'MMM', /* or MM */
>      year: 'yyyy',
>    },
>  },
>  timeAxis: {
>    scale: 'month',
>    step: 1,
>  },
> };
>
> let eventData = [];
> // makeMarker simply wraps a date into a 'point' item, with a content
> eventData.push(makeMarker(dpStart)); 
> eventData.push(makeMarker(dpEnd));
> for (evt in this.props.allEvents) {  
>   eventData.push(evt);
> }
>
> return (
>   \<Timeline options={options} items={eventData} />
> );

let me know if you require any other details..

**Comment by jonathanchrisp** [comment] 2017-05-31 12:07
Hi @prabuvenkat, I've replicated your issue locally and this appears to have been caused by the latest release of `vis.js` unfortunately. I'll raise this on their repo and link to this issue. Hopefully, this has already been raised and in the process of being fixed. 

Please see my testing below: 

## v4.19.1
![screen shot 2017-05-31 at 10 02 58 pm](https://cloud.githubusercontent.com/assets/406799/26631205/532d108e-464d-11e7-979b-3ab181ab1e40.png)

## v4.20.0
![screen shot 2017-05-31 at 10 00 11 pm](https://cloud.githubusercontent.com/assets/406799/26631177/3cd6a340-464d-11e7-976c-ba41b5a5eabc.png)

Just to note, I changed your code in places but I've replicated the issue anyhow.

**Comment by jonathanchrisp** [comment] 2017-05-31 12:11
Hey @prabuvenkat, please see issue linked above, it has already been raised so hopefully this should be fixed soon. The quick fix for you would to simply fall back to the previous version (v4.19.1). I'll keep this issue open until the associated issue has been resolved.

**Closed** 2017-07-04 07:11 UTC
